DROP TABLE IF EXISTS ADDRESSES;
CREATE TABLE ADDRESSES(
  addr_id INT(11) AUTO_INCREMENT PRIMARY KEY,
  street VARCHAR(50) NOT NULL,
  city VARCHAR(50) NOT NULL,
  state VARCHAR (50) NOT NULL,
  zip VARCHAR(50) DEFAULT NULL,
  country VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS STUDENTS;
CREATE TABLE STUDENTS(
  stud_id INT(11) AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL ,
  email VARCHAR(50) NOT NULL,
  phone VARCHAR(15) DEFAULT NULL,
  dbo DATE DEFAULT NULL,
  pic BLOB DEFAULT NULL,
  addr_id INT(11),
  FOREIGN KEY (addr_id) REFERENCES ADDRESSES(addr_id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS TUTORS;
CREATE TABLE TUTORS(
  tutor_id INT(11) AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  dob DATE DEFAULT NULL,
  bio LONGTEXT DEFAULT NULL,
  pic BLOB DEFAULT null,
  addr_id INT(11),
  FOREIGN KEY (addr_id) REFERENCES ADDRESSES(addr_id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS COURSES;
CREATE TABLE COURSES(
  course_id INT(11) AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  decription VARCHAR(512) DEFAULT NULL,
  start_date DATE DEFAULT  NULL,
  end_date DATE DEFAULT null,
  tutor_id int(11),
  FOREIGN KEY (tutor_id) REFERENCES TUTORS(tutor_id)
);

DROP TABLE  IF EXISTS COURSE_ENROLLMENT;
CREATE TABLE COURSE_ENROLLMENT(
  course_id INT(11) NOT NULL,
  stud_id INT(11) NOT NULL,
  PRIMARY KEY (course_id, stud_id),
  FOREIGN KEY (course_id) REFERENCES COURSES(course_id),
  FOREIGN KEY (stud_id) REFERENCES STUDENTS(stud_id)
);